### ISSUE TITLE
Requirement Analysis

### ISSUE THREAD

**Issue by abhisingh1** [abhisingh1/LoyaltySystem#1]
Requirement Analysis Brainstorm:
https://docs.google.com/document/d/1XYnJKS2DNqGOMWUgfx6gBRBRCtTuduhQykJ_DJRqBC0/edit

Fully-Dressed Use Cases: 
https://docs.google.com/document/d/1G-_XdGSgKx84HuHDhb74pNP5nHXd3md-rB2tnl-jTIY/edit?ts=57e053f7

Supplementary Specifications: https://docs.google.com/document/d/1LoJFdZx2Ifo99WXuNsppx_uOthTeAITL3GY-nNqSpCg/edit

**Comment by akhilg96** [comment]
Submitted following 4 documents:

[Group1_Conceptual_Diagram.pdf](https://github.com/abhisingh1/LoyaltySystem/files/497110/Group1_Conceptual_Diagram.pdf)
[Group1_Supp_Specs.pdf](https://github.com/abhisingh1/LoyaltySystem/files/497113/Group1_Supp_Specs.pdf)
[Group1_Use_Case_Diagram.pdf](https://github.com/abhisingh1/LoyaltySystem/files/497112/Group1_Use_Case_Diagram.pdf)
[Group1_Use_Cases.pdf](https://github.com/abhisingh1/LoyaltySystem/files/497111/Group1_Use_Cases.pdf)
