### ISSUE TITLE
Use Case 8: Login Credentials

### ISSUE THREAD

**Issue by akhilg96** [abhisingh1/LoyaltySystem#3]
For this use-case, are we dealing with setting up an account if the user is new OR is that part of customer/business registration? I was thinking, maybe, if a person doesn't have an account they click on some "sign up" button and then we show them two options like "business registration" and "customer registration." And then our Use Cases 1 & 2 would need to take over from there. Sounds good?

**Comment by abhisingh1** [comment]
Sounds good.

**Comment by gdcolella** [comment]
The business signup is much less frequent and more solicited than the consumer signup, so I don't think they necessarily need to be in the same place - there might just be a button on the homepage that's like "Want to see your business here? Click here for information!".

Either way works though as long as the difference is clear to the average user, I think.
