### ISSUE TITLE
Use Case 10: Customers Viewing Their Transaction History

### ISSUE THREAD

**Issue by AndySin** [abhisingh1/LoyaltySystem#4]
Will transaction history be based off of time or number of entries (i.e displaying entries in the past month/year rather than displaying the last 50 or 100 transactions)? Will records be stored indefinitely server-side, or will they eventually be aged out based on oldest transaction to reduce server strain?

**Comment by gdcolella** [comment]
Hmm, I think saving transactions for the past 6 months would be reasonable; it's not very much data. If it became a problem we could test to see how much it would actually take up and maybe charge business more for longer retention policies if they require them?
