### ISSUE TITLE
Important Use Case Missing? 

### ISSUE THREAD

**Issue by akhilg96** [abhisingh1/LoyaltySystem#5]
I don't think we have a use case that goes over how customers are awarded with points upon purchase. I see Customer Point Redemption (Use case 9 in the fully-dressed use case doc) but it doesn't really go over the process. Should we  include a use case that goes over that process? I feel like this is probably one of the most fundamental ones. We might want to replace one of our existing requirements that we haven't converted into a fully-dressed use case yet, if needed.

**Comment by gdcolella** [comment]
3. Registering customer purchases is intended to cover this, but it's not as clearly named as it should be. Awarding points should be done when the customer's purchase is registered (otherwise, they wouldn't register the purchase with our system at all)

**Comment by akhilg96** [comment]
@AndySin Looks like you might have to change that use-case a bit then... We definitely want something that covers how customers are awarded with points upon purchasing an item.

**Comment by gdcolella** [comment]
Sorry, I used the wrong numbering scheme when referring to 3). This use-case is actually one of mine represented in the final document as 13) - I will include this aspect.

**Comment by akhilg96** [comment]
My bad. I see it now. "Registering customer purchases" use case
